# docker-compose.yml
version: "3.8"

services:
  jenkins:
    build: .
    container_name: custom-jenkins
    ports:
      - "8080:8080"   # Jenkins web UI
      - "50000:50000" # For agent connections
    volumes:
      - C:/Playground_Raiyeem/files/matiKata/ci_cd_with_jenkins/jenkins_home:/var/jenkins_home
    restart: unless-stopped
